//! Buffered UART
//!
//! This UART implementation will interrupt any time a byte is received and read the byte immediately
//! into a ring-buffer backed by a user-provided buffer. This is useful when the RX FIFO is particularly
//! small, but may be less efficient as we need to interrupt more often and copy bytes from the ring-buffer
//! into the read buffer.
//!
//! This change only affects RX. TX behavior remains unchanged.
use super::*;

/// Buffered UART interrupt handler binding.
pub struct BufferedInterruptHandler<T: Instance> {
    _phantom: PhantomData<T>,
}

impl<T: Instance> Handler<T::Interrupt> for BufferedInterruptHandler<T> {
    unsafe fn on_interrupt() {
        let mut pushed_any = false;
        while T::info()
            .reg
            .ctrl()
            .read()
            .uart_ctrl_rx_nempty()
            .bit_is_set()
        {
            // SAFETY: Ring buffer has been initialized and we are the only writer
            let mut writer = unsafe { T::buffer().writer() };
            let byte = T::info().reg.data().read().uart_data_rtx().bits();
            if writer.push_one(byte) {
                pushed_any = true;
            } else {
                break;
            }
        }

        if pushed_any {
            T::info().rx_waker.wake();
        }

        check_wake_tx_empty::<T>();
    }
}

/// RX-buffered UART driver.
pub struct BufferedUart<'d> {
    rx: BufferedUartRx<'d>,
    tx: UartTx<'d, Async>,
}

impl<'d> BufferedUart<'d> {
    /// Creates a new RX-buffered UART driver with given baud rate.
    ///
    /// # Errors
    ///
    /// Returns [`Error::NotSupported`] if UART is not supported.
    pub fn new<T: Instance>(
        _instance: Peri<'d, T>,
        rx_buffer: &'d mut [u8],
        baud_rate: u32,
        flow_control: bool,
        _irq: impl Binding<T::Interrupt, BufferedInterruptHandler<T>> + 'd,
    ) -> Result<Self, Error> {
        let rx = BufferedUartRx::new(_instance, rx_buffer, baud_rate, flow_control, _irq)?;
        let tx = UartTx::new_inner::<T>(None)?;
        Ok(Self { rx, tx })
    }

    /// Splits the buffered UART driver into separate [`BufferedUartRx`] and [`UartTx`] drivers.
    ///
    /// Helpful for sharing the buffered UART among receiver/transmitter tasks.
    pub fn split(self) -> (BufferedUartRx<'d>, UartTx<'d, Async>) {
        (self.rx, self.tx)
    }

    /// Splits the buffered UART driver into separate [`BufferedUartRx`] and [`UartTx`] drivers by mutable reference.
    ///
    /// Helpful for sharing the buffered UART among receiver/transmitter tasks without destroying the original [`BufferedUart`] instance.
    pub fn split_ref(&mut self) -> (&mut BufferedUartRx<'d>, &mut UartTx<'d, Async>) {
        (&mut self.rx, &mut self.tx)
    }

    /// Reads bytes from RX ring buffer, blocking until enough are available to fill `buf`.
    pub fn blocking_read(&mut self, buf: &mut [u8]) {
        self.rx.blocking_read(buf);
    }

    /// Reads bytes from RX ring buffer, waiting until enough are available to fill `buf`.
    pub fn read(&mut self, buf: &mut [u8]) -> impl Future<Output = ()> {
        self.rx.read(buf)
    }

    /// Writes bytes to TX FIFO, blocking if full.
    pub fn blocking_write(&mut self, buf: &[u8]) {
        self.tx.blocking_write(buf);
    }

    /// Writes bytes to TX FIFO, waiting if full.
    pub fn write(&mut self, buf: &[u8]) -> impl Future<Output = Result<(), Error>> {
        self.tx.write(buf)
    }

    /// Blocks until the TX FIFO is empty and has finished transmitting.
    pub fn blocking_flush(&mut self) {
        self.tx.blocking_flush();
    }

    /// Waits until the TX FIFO is empty and has finished transmitting.
    pub fn flush(&mut self) -> impl Future<Output = ()> {
        self.tx.flush()
    }
}

/// RX-only buffered UART driver.
pub struct BufferedUartRx<'d> {
    info: Info,
    buffer: &'static RingBuffer,
    _phantom: PhantomData<&'d ()>,
}

// Allows for use in a Mutex (to share safely between harts and tasks)
// Revisit: Is this actually safe?
// SAFETY: This is a consequence of the register block generated by the PAC being !Sync,
// and since we hold a reference to it that makes us !Send
unsafe impl<'d> Send for BufferedUartRx<'d> {}

impl<'d> BufferedUartRx<'d> {
    fn enable_irq_rx_nempty(&mut self) {
        critical_section::with(|_| {
            self.info
                .reg
                .ctrl()
                .modify(|_, w| w.uart_ctrl_irq_rx_nempty().set_bit())
        });
    }

    fn disable_irq_rx_nempty(&mut self) {
        critical_section::with(|_| {
            self.info
                .reg
                .ctrl()
                .modify(|_, w| w.uart_ctrl_irq_rx_nempty().clear_bit())
        });
    }

    fn read_inner(&mut self, buf: &mut [u8]) {
        self.disable_irq_rx_nempty();

        // SAFETY: The ring buffer has been initialized and this is the only reader that exists
        let mut reader = unsafe { self.buffer.reader() };

        // The loop is to account for ring buffer wrap-around, even though there are enough bytes
        // immediately available, length of data might be less if at end of ring buffer
        let mut copied = 0;
        while copied < buf.len() {
            copied += reader.pop(|data| {
                let len = core::cmp::min(data.len(), buf.len() - copied);
                buf[copied..copied + len].copy_from_slice(&data[..len]);
                len
            });
        }

        self.enable_irq_rx_nempty();
    }

    /// Creates a new buffered RX-only UART driver with given baud rate.
    ///
    /// Enables hardware flow control if `flow_control` is true.
    ///
    /// # Errors
    ///
    /// Returns [`Error::NotSupported`] if UART is not supported.
    pub fn new<T: Instance>(
        _instance: Peri<'d, T>,
        buffer: &'d mut [u8],
        baud_rate: u32,
        flow_control: bool,
        _irq: impl Binding<T::Interrupt, BufferedInterruptHandler<T>> + 'd,
    ) -> Result<Self, Error> {
        if !T::supported() {
            return Err(Error::NotSupported);
        }

        // Mark RX as active
        T::info().active.rx.store(true, Ordering::Release);

        // SAFETY: It is valid to enable UART interrupt here
        unsafe { T::Interrupt::enable() }

        // SAFETY: The function signature guarantees buffer is always valid memory
        unsafe { T::buffer().init(buffer.as_mut_ptr(), buffer.len()) }

        init::<T>(baud_rate, flow_control);
        let mut uart = Ok(Self {
            info: T::info(),
            buffer: T::buffer(),
            _phantom: PhantomData,
        })?;

        uart.enable_irq_rx_nempty();
        Ok(uart)
    }

    /// Reads bytes from RX ring buffer, blocking until enough are available to fill `buf`.
    pub fn blocking_read(&mut self, buf: &mut [u8]) {
        while self.buffer.available() < buf.len() {}
        self.read_inner(buf);
    }

    /// Reads bytes from RX ring buffer, waiting until enough are available to fill `buf`.
    pub async fn read(&mut self, buf: &mut [u8]) {
        poll_fn(|cx| {
            self.info.rx_waker.register(cx.waker());
            if self.buffer.available() >= buf.len() {
                self.read_inner(buf);
                Poll::Ready(())
            } else {
                Poll::Pending
            }
        })
        .await
    }
}

// Convenience for writing formatted strings to buffered UART
impl<'d> core::fmt::Write for BufferedUart<'d> {
    fn write_str(&mut self, s: &str) -> core::fmt::Result {
        self.blocking_write(s.as_bytes());
        Ok(())
    }
}

impl<'d> embedded_hal_02::blocking::serial::Write<u8> for BufferedUart<'d> {
    type Error = core::convert::Infallible;

    fn bwrite_all(&mut self, buffer: &[u8]) -> Result<(), Self::Error> {
        self.blocking_write(buffer);
        Ok(())
    }

    fn bflush(&mut self) -> Result<(), Self::Error> {
        self.blocking_flush();
        Ok(())
    }
}

impl<'d> embedded_io::ErrorType for BufferedUart<'d> {
    type Error = Error;
}

impl<'d> embedded_io::Read for BufferedUart<'d> {
    fn read(&mut self, buf: &mut [u8]) -> Result<usize, Self::Error> {
        self.blocking_read(buf);
        Ok(buf.len())
    }
}

impl<'d> embedded_io_async::Read for BufferedUart<'d> {
    async fn read(&mut self, buf: &mut [u8]) -> Result<usize, Self::Error> {
        self.read(buf).await;
        Ok(buf.len())
    }
}

impl<'d> embedded_io::Write for BufferedUart<'d> {
    fn write(&mut self, buf: &[u8]) -> Result<usize, Self::Error> {
        self.blocking_write(buf);
        Ok(buf.len())
    }

    fn flush(&mut self) -> Result<(), Self::Error> {
        self.blocking_flush();
        Ok(())
    }
}

impl<'d> embedded_io_async::Write for BufferedUart<'d> {
    async fn write(&mut self, buf: &[u8]) -> Result<usize, Self::Error> {
        self.write(buf).await.map(|_| buf.len())
    }

    async fn flush(&mut self) -> Result<(), Self::Error> {
        self.flush().await;
        Ok(())
    }
}

impl<'d> embedded_io::ErrorType for BufferedUartRx<'d> {
    type Error = Error;
}

impl<'d> embedded_io::Read for BufferedUartRx<'d> {
    fn read(&mut self, buf: &mut [u8]) -> Result<usize, Self::Error> {
        self.blocking_read(buf);
        Ok(buf.len())
    }
}

impl<'d> embedded_io_async::Read for BufferedUartRx<'d> {
    async fn read(&mut self, buf: &mut [u8]) -> Result<usize, Self::Error> {
        self.read(buf).await;
        Ok(buf.len())
    }
}
