[workspace]

[package]
name = "neorv32-riscvrt-examples"
version = "0.1.0"
edition = "2024"

[dependencies]
embassy-neorv32 = { path = "../../", default-features = false, features = [
    "rt",
] }
riscv = "0.15.0"
riscv-rt = "0.16.0"
panic-halt = "1.0.0"
