#!/bin/bash

# Set this to your neorv32 repo path
BASE="$HOME/Documents/neorv32"

# image_gen says it takes ELF but really seems to need raw bin? so convert.
llvm-objcopy $1 -O binary "$1.bin"

# Convert bin to bootloader bin format neorv32 expects
"$BASE/sw/image_gen/image_gen" -app_bin "$1.bin" "$1-bl"

# Connect to bootloader over serial using picocom
cd target/riscv32imc-unknown-none-elf/release
sudo picocom /dev/ttyUSB0 -b 19200 --imap lfcrlf --omap crlf --send-cmd="ascii-xfr -s -n"
# Manually follow these steps:
#
# Press reset button
# Hit any key
# u (Upload)
# Ctrl+A Ctrl+S (send file)
# type mybin
