#!/bin/bash

# Set this to your neorv32 repo path
BASE="$HOME/Documents/neorv32"

# image_gen says it takes ELF but really seems to need raw bin? so convert.
llvm-objcopy $1 -O binary $1

# Generate the VHD image then place it in neorv32 core
"$BASE/sw/image_gen/image_gen" -app_vhd $1 neorv32_application_image.vhd
mv neorv32_application_image.vhd "$BASE/rtl/core"

# Run neorv32 sim script
sh "$BASE/sim/ghdl.sh"