[package]
name = "neorv32-pac"
version = "0.1.0"
edition = "2024"
authors = ["Kurtis Dinelle <kurtis.dinelle@gmail.com>"]
license = "MIT"
repository = "https://github.com/kurtjd/embassy-neorv32"

[dependencies]
